---
title: "Deber_IntroducciónR"
author: "Fernanda Minango"
date: "26/2/2022"
output:
  html_document:
    fig_height: 6
    fight_width: 8
    theme: journal
    toc: yes
    toc_depht: 4
    toc_float:
      collapsed: no
      smooth_scroll: yes
---

```{r Setup,include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Deber Introducción R:
### Ejercicio N°1

```{r Ej1}
# Ejercicio N°1:

ciudad <- "Quito"

print(ciudad)

```

### Ejercicio N°2:


```{r Ej2}

# Ejercicio N°2:

pais_andes <- c("Argentina", "Ecuador", "Bolivia", "Chile", "Colombia", "Perú", "Venezuela")

print(pais_andes)
```

### Ejercicio N°3:

```{r Ej3}

### Ejercicio N°3:

Datos_donadores = data.frame(num_donador = paste0("Donador", 1:12), Nombre = c("Joseph", "Nayeli", "Carolina", "Juan", "Gabriel", "Cristina", "Mateo", "Franklin", "George", "Daniel", "Danilo", "Anthony"), Edad = c("21", "23", "20", "19", "25", "20", "20", "18", "24", "22", "23", "17"), VecesDonador = sample(2:10, 12, replace = TRUE), Pintas_donadas =sample(0.5:1.5, 12, replace = TRUE) )

Datos_donadores
```

### Ejecicio N°4:

#### Ejecicio 4 sección 1:

```{r Ej4-1}

# Ejercicio N°4-1:

?DNase

print(head(DNase, 4))

concentracion = subset(DNase, conc >= 0.1 & conc <= 0.2)

print(concentracion)

```
* Ejercicio 4-2:


```{r Ej4-2}

# Ejercicio 4-2:

?DNase

concentracion2 = subset(DNase, Run != 2 & conc > 0.2 & density <= 1.0)

print(concentracion2)

```

